### ISSUE TITLE
Models

### ISSUE THREAD

**Issue by 11mLLM** [11mLLM/11mLLM#4]
## Task
- [ ]  Flan
- [ ]  ChatGPT
- [ ]  LLaMA
- [ ]  GPT-4
- [ ]  LLM Collection

**Comment by letsbe-x** [comment]
해당 Projects의 Assignees 권한이 저에게 없는 것으로 보입니다 @11mLLM

**Comment by 11mLLM** [comment]
@letsbe-x 제대로 assign 하셨습니다!  어느 부분 말씀하시는 걸까요?

**Comment by socar-letsbe** [comment]
> @letsbe-x 제대로 assign 하셨습니다!  어느 부분 말씀하시는 걸까요?

해당 project에서 self-assign이 안되어서 요청드렸어요 🙏

**Comment by letsbe-x** [comment]
![Image](https://github.com/11mLLM/11mLLM/assets/26156900/5e0f4ee7-05d3-47a5-96c6-876c80587fb2)

해당 Project의 self-assign이 안되어서 요청드렸습니다 😄

**Comment by 11mLLM** [comment]
할당 완료!

**Comment by 11mLLM** [comment]
리뷰 1차 완료 ✅
